version: '3.4'

services:
  agenda_service:
    image: ${DOCKER_REGISTRY-}dockeragenda
    build:
      context: .
      dockerfile: src/DockerAgenda/Dockerfile
    entrypoint:
     - CONNECTIONSTRINGS:Server=sql_agenda_service,1433;Database=DockerAgenda_Db;MultipleActiveResultSets=true;User ID=sa;Password=Pass@word
    networks:
     - net_agenda
    depends_on:
     - sql_agenda_service

  sql_agenda_service:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
     - SA_PASSWORD=Pass@word
     - ACCEPT_EULA=Y
    volumes:
     - sql_agenda_service_volume:/var/opt/mssql
    networks:
     - net_agenda

volumes:
  sql_agenda_service_volume:

networks:
  net_agenda:
    driver: bridge