version: '3.9'

services:
  agenda_service:
    image: marcioalmeidarosa/api_agenda:latest
    hostname: agenda_service
    labels:
      - NAME=agenda_service
    environment:
     - CONNECTION__CONNECTIONSTRINGS=Server=sql_agenda_service,1433;Database=DockerAgenda_Db;MultipleActiveResultSets=true;User ID=sa;Password=Pass@word
    networks:
     - net_agenda
    ports:
      - "80:80"
      - "443:443"
    depends_on:
     - sql_agenda_service
    volumes:
      - api_log_volume:/logs

  sql_agenda_service:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sql_agenda_service
    hostname: sql_agenda_service
    labels:
      - NAME=sql_agenda_service
    environment:
     - SA_PASSWORD=Pass@word
     - ACCEPT_EULA=Y
    volumes:
     - sql_agenda_service_volume:/var/opt/mssql
    networks:
     - net_agenda
    ports:
      - "1433:1433"

volumes:
  sql_agenda_service_volume:

  api_log_volume:

networks:
  net_agenda:
    driver: bridge